<div class="nwc-calculator-wrapper">
    <div class="container-fluid">
        <!-- Header -->
        <div class="nwc-header">
            <div class="nwc-brand-label">MINTED MOOLA</div>
            <h1 class="nwc-title">
                <span class="nwc-icon">💰</span> Net Worth Calculator
            </h1>
            <p class="nwc-subtitle">Fame. Fortune. The Full Story.</p>
        </div>

        <div class="nwc-container">
            <!-- Main Content Grid -->
            <div class="row">
                <!-- Left Column: Input Forms -->
                <div class="col-lg-6">
                    <!-- ASSETS SECTION -->
                    <div class="nwc-section nwc-assets-section">
                        <div class="nwc-section-header">
                            <h2>
                                <span class="nwc-badge nwc-badge-assets">📈</span>
                                Assets
                            </h2>
                            <span class="nwc-section-total" id="assetsTotal">$0.00</span>
                        </div>

                        <div class="nwc-categories" id="assetsCategories">
                            <!-- Asset categories generated by JS -->
                        </div>

                        <button class="btn btn-success btn-sm w-100 mt-3" id="addAssetBtn">
                            <i class="fas fa-plus"></i> Add New Asset
                        </button>
                    </div>

                    <!-- LIABILITIES SECTION -->
                    <div class="nwc-section nwc-liabilities-section">
                        <div class="nwc-section-header">
                            <h2>
                                <span class="nwc-badge nwc-badge-liabilities">📉</span>
                                Liabilities
                            </h2>
                            <span class="nwc-section-total" id="liabilitiesTotal">$0.00</span>
                        </div>

                        <div class="nwc-categories" id="liabilitiesCategories">
                            <!-- Liability categories generated by JS -->
                        </div>

                        <button class="btn btn-danger btn-sm w-100 mt-3" id="addLiabilityBtn">
                            <i class="fas fa-plus"></i> Add New Liability
                        </button>
                    </div>
                </div>

                <!-- Right Column: Results & Charts -->
                <div class="col-lg-6">
                    <!-- NET WORTH SUMMARY -->
                    <div class="nwc-summary-card">
                        <div class="nwc-summary-item">
                            <span class="nwc-summary-label">Total Assets</span>
                            <span class="nwc-summary-value nwc-assets-color" id="summaryAssets">$0.00</span>
                        </div>
                        <div class="nwc-summary-divider"></div>
                        <div class="nwc-summary-item">
                            <span class="nwc-summary-label">Total Liabilities</span>
                            <span class="nwc-summary-value nwc-liabilities-color" id="summaryLiabilities">$0.00</span>
                        </div>
                        <div class="nwc-summary-divider nwc-summary-divider-thick"></div>
                        <div class="nwc-summary-item nwc-summary-networth">
                            <span class="nwc-summary-label">Your Net Worth</span>
                            <span class="nwc-summary-value nwc-networth-value" id="summaryNetWorth">$0.00</span>
                        </div>
                    </div>

                    <!-- CHARTS -->
                    <div class="nwc-charts-container">
                        <div class="nwc-chart-box">
                            <h3>Net Worth Breakdown</h3>
                            <canvas id="breakdownChart" height="80"></canvas>
                        </div>

                        <div class="nwc-chart-box">
                            <h3>Assets by Category</h3>
                            <canvas id="assetsChart" height="80"></canvas>
                        </div>

                        <div class="nwc-chart-box">
                            <h3>Liabilities by Category</h3>
                            <canvas id="liabilitiesChart" height="80"></canvas>
                        </div>
                    </div>

                    <!-- ACTION BUTTONS -->
                    <div class="nwc-actions">
                        <button class="btn btn-primary w-100" id="exportPdfBtn">
                            <i class="fas fa-download"></i> Export as PDF
                        </button>
                        <button class="btn btn-outline-secondary w-100" id="exportCsvBtn">
                            <i class="fas fa-file-csv"></i> Export as CSV
                        </button>
                        <button class="btn btn-outline-danger w-100" id="resetBtn">
                            <i class="fas fa-redo"></i> Reset Calculator
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Custom Modal Overlay -->
<div id="nwc-modal-overlay" class="nwc-modal-overlay">
    <div class="nwc-modal-dialog">
        <div class="nwc-modal-header">
            <h3 id="categoryModalLabel">Add Item</h3>
            <button type="button" class="nwc-modal-close" id="closeModalBtn">&times;</button>
        </div>
        <div class="nwc-modal-body">
            <div class="nwc-form-group">
                <label for="itemName">Item Name</label>
                <input type="text" class="nwc-form-input" id="itemName" placeholder="e.g., Savings Account" autocomplete="off">
            </div>
            <div class="nwc-form-group">
                <label for="itemAmount">Amount ($)</label>
                <input type="number" class="nwc-form-input" id="itemAmount" placeholder="0.00" step="0.01" min="0" autocomplete="off">
            </div>
            <div class="nwc-form-group">
                <label for="itemCategory">Category</label>
                <select class="nwc-form-input nwc-form-select" id="itemCategory"></select>
            </div>
        </div>
        <div class="nwc-modal-footer">
            <button type="button" class="btn btn-secondary" id="cancelModalBtn">Cancel</button>
            <button type="button" class="btn btn-primary" id="saveItemBtn">Save Item</button>
        </div>
    </div>
</div>

<div id="nwc-notification" class="nwc-notification"></div>
