<div class="nwc-calculator-wrapper">
    <div class="container-fluid">
        <!-- Header -->
        <div class="nwc-header">
            <div class="nwc-brand-label">MINTED MOOLA</div>
            <h1 class="nwc-title">
                <span class="nwc-icon">💰</span> Net Worth Calculator
            </h1>
            <p class="nwc-subtitle">Fame. Fortune. The Full Story.</p>
        </div>

        <div class="nwc-container">
            <!-- Quick Add Form -->
            <div class="nwc-quick-add-section" id="quickAddForm" style="display:none;">
                <div class="nwc-quick-add-header">
                    <h3 id="formTitle">Add New Item</h3>
                    <button class="nwc-quick-add-close" onclick="calculator.closeForm()">×</button>
                </div>
                <div class="nwc-quick-add-body">
                    <div class="nwc-form-group">
                        <label>Item Name</label>
                        <input type="text" class="nwc-form-input" id="itemName" placeholder="e.g., Savings Account">
                    </div>
                    <div class="nwc-form-group">
                        <label>Amount ($)</label>
                        <input type="number" class="nwc-form-input" id="itemAmount" placeholder="0.00" step="0.01" min="0">
                    </div>
                    <div class="nwc-form-group">
                        <label>Category</label>
                        <select class="nwc-form-input" id="itemCategory"></select>
                    </div>
                    <div class="nwc-form-group">
                        <button class="btn btn-primary w-100" onclick="calculator.saveItem()">Save Item</button>
                        <button class="btn btn-secondary w-100 mt-2" onclick="calculator.closeForm()">Cancel</button>
                    </div>
                </div>
            </div>

            <!-- Main Content Grid -->
            <div class="row">
                <!-- Left Column: Input Forms -->
                <div class="col-lg-6">
                    <!-- ASSETS SECTION -->
                    <div class="nwc-section nwc-assets-section">
                        <div class="nwc-section-header">
                            <h2>
                                <span class="nwc-badge nwc-badge-assets">📈</span>
                                Assets
                            </h2>
                            <span class="nwc-section-total" id="assetsTotal">$0.00</span>
                        </div>

                        <div class="nwc-categories" id="assetsCategories">
                            <!-- Asset categories generated by JS -->
                        </div>
                    </div>

                    <!-- LIABILITIES SECTION -->
                    <div class="nwc-section nwc-liabilities-section">
                        <div class="nwc-section-header">
                            <h2>
                                <span class="nwc-badge nwc-badge-liabilities">📉</span>
                                Liabilities
                            </h2>
                            <span class="nwc-section-total" id="liabilitiesTotal">$0.00</span>
                        </div>

                        <div class="nwc-categories" id="liabilitiesCategories">
                            <!-- Liability categories generated by JS -->
                        </div>
                    </div>
                </div>

                <!-- Right Column: Results & Charts -->
                <div class="col-lg-6">
                    <!-- NET WORTH SUMMARY -->
                    <div class="nwc-summary-card">
                        <div class="nwc-summary-item">
                            <span class="nwc-summary-label">Total Assets</span>
                            <span class="nwc-summary-value nwc-assets-color" id="summaryAssets">$0.00</span>
                        </div>
                        <div class="nwc-summary-divider"></div>
                        <div class="nwc-summary-item">
                            <span class="nwc-summary-label">Total Liabilities</span>
                            <span class="nwc-summary-value nwc-liabilities-color" id="summaryLiabilities">$0.00</span>
                        </div>
                        <div class="nwc-summary-divider nwc-summary-divider-thick"></div>
                        <div class="nwc-summary-item nwc-summary-networth">
                            <span class="nwc-summary-label">Your Net Worth</span>
                            <span class="nwc-summary-value nwc-networth-value" id="summaryNetWorth">$0.00</span>
                        </div>
                    </div>

                    <!-- CHARTS -->
                    <div class="nwc-charts-container">
                        <div class="nwc-chart-box">
                            <h3>Net Worth Breakdown</h3>
                            <canvas id="breakdownChart" height="80"></canvas>
                        </div>

                        <div class="nwc-chart-box">
                            <h3>Assets by Category</h3>
                            <canvas id="assetsChart" height="80"></canvas>
                        </div>

                        <div class="nwc-chart-box">
                            <h3>Liabilities by Category</h3>
                            <canvas id="liabilitiesChart" height="80"></canvas>
                        </div>
                    </div>

                    <!-- ACTION BUTTONS -->
                    <div class="nwc-actions">
                        <button class="btn btn-primary w-100" id="exportPdfBtn">
                            <i class="fas fa-download"></i> Export as PDF
                        </button>
                        <button class="btn btn-outline-secondary w-100" id="exportCsvBtn">
                            <i class="fas fa-file-csv"></i> Export as CSV
                        </button>
                        <button class="btn btn-outline-danger w-100" id="resetBtn">
                            <i class="fas fa-redo"></i> Reset Calculator
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="nwc-notification" class="nwc-notification"></div>
